#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/usr/arch/nrn/neuron/.data"
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/usr/arch/nrn/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/u/btessler/netpyneca3/x86_64/.libs/libnrnmech.so" "$@"
